# Generated by Django 4.2.7 on 2023-12-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_categories_items_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
