# Generated by Django 4.2.7 on 2023-12-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_items_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Xtra Large'), ('XXL', 'Xtra Xtra Large')], null=True),
        ),
    ]
