# Generated by Django 4.2.7 on 2023-12-12 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_items_image_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='size',
        ),
    ]
